### ISSUE TITLE
Arrays of numbers print as empty objects

### ISSUE THREAD

**Issue by cephirothdy2j** [rodrigo-morais/ember-json-pretty#5]
Given this JSON input ...

"address": {
	"address1": "3925 Brookside Pwky",
	"city": "Alpharetta",
	"region": "GA",
	"zip": "30040",
	"timezoneId": "America/Chicago",
	"loc": [-84.2479169,34.0592993],
	"country": "US"
}

The plugin prints the "loc" values (each a number) as two empty objects ...

address : {
address1 : 3925 Brookside Pwky ,
city : Alpharetta ,
region : GA ,
zip : 30040 ,
timezoneId : America/Chicago ,
loc : [             {             } ,             {             }          ] ,
country : US

Converting the numbers to strings makes them print as expected. Note that the empty object error happens whether the number is an integer or a float.

**Comment by rodrigo-morais** [comment]
@cephirothdy2j,

Sorry for the delay to fix this issue.
I solved the problem, please, confirm if it works to you.
